2020-03-10 16:07:40,706 [INFO]: #  From Excel import testsuite success
2020-03-10 17:55:10,653 [INFO]: #  ==================================================
2020-03-10 17:55:10,662 [INFO]: #  *** SETUP testcase ***
2020-03-10 18:13:02,854 [INFO]: #  >>> Run the TestCase: HOME_001|打开百度
2020-03-10 18:13:02,862 [INFO]: #  Run the Step: 1|通用|OPEN|通用-百度搜索链接
2020-03-10 18:13:05,391 [INFO]: #  --- success ---
2020-03-10 18:13:05,605 [INFO]: #  Run the Step: 2|百度搜索页面|CHECK|通用-页面title
2020-03-10 18:13:05,645 [INFO]: #  DATA:'百度一下\\，你就知道'
2020-03-10 18:13:05,670 [INFO]: #  REAL:'百度一下，你就知道'
2020-03-10 18:13:06,162 [ERROR]: #  +++ failure +++
Traceback (most recent call last):
  File "D:\Project\sweetest\sweetest\sweetest\keywords\web.py", line 23, in title
    assert data['text'] == g.driver.title
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\sweetest\sweetest\sweetest\testcase.py", line 137, in run
    element = getattr(web, step['keyword'].lower())(step)
  File "D:\Project\sweetest\sweetest\sweetest\keywords\web.py", line 93, in check
    var[by] = getattr(Common, by)(data, output)
  File "D:\Project\sweetest\sweetest\sweetest\keywords\web.py", line 25, in title
    raise Exception(f'Check Failure, DATA:{data["text"]}, REAL:{g.driver.title}')
Exception: Check Failure, DATA:百度一下\，你就知道, REAL:百度一下，你就知道
